Repository nodexpertsdev/RnD, pull requests merged in 2019-04, with the labels that each got.

#39 Feature/37
  expressEngine/model/collection/product.js
  expressEngine/product/service/product.js
Labels: bug

#49 bug/47
  expressEngine/user/controller/user.js
Labels: bug

#60 Feature/54
  PR_Guide.md
Labels: Docs

#82 Feature/57
  expressEngine/doc/swagger.json
Labels: Docs

#73 feature/65
  expressEngine/lib/routeHelper.js
  expressEngine/server.js
Labels: enhancement, feature

#53 Get Functionality of users: Feature/17
  expressEngine/.eslintrc.json
  expressEngine/cms/user/error.js
  expressEngine/lib/service/base.js
  expressEngine/lib/service/db.js
  expressEngine/package.json
  expressEngine/user/controller/user.js
  expressEngine/user/route.js
  expressEngine/user/service/user.js
  expressEngine/user/utils/index.js
  expressEngine/user/utils/user.js
Labels: feature

#74 design: created file to follow guidelines while working on an issue(#64)
  ISSUE_AND_PR_GUIDE.md
Labels: Docs

#78 fix validation password
  expressEngine/model/lib/index.js
Labels: In Progress

#58 updated branch (#35)
  expressEngine/lib/parser/base.js
  expressEngine/lib/validationHandler/index.js
  expressEngine/lib/validationHandler/validateRequired.js
  expressEngine/order/service/order.js
  expressEngine/product/service/product.js
  expressEngine/route.js
  expressEngine/user/controller/user.js
  expressEngine/user/service/user.js
Labels: feature, updated branch

#83 feature/66: Create swagger document for customer
  expressEngine/doc/swagger.json
Labels: doc

#94 feature/91
  expressEngine/customer/service/customer.js
  expressEngine/model/collection/customer.js
Labels: enhancement

#101 Feature/18
  expressEngine/cms/user/error.js
  expressEngine/login/controller/index.js
  expressEngine/login/controller/login.js
  expressEngine/login/route.js
  expressEngine/login/service/index.js
  expressEngine/login/service/service.js
  expressEngine/model/collection/userToken.js
  expressEngine/model/index.js
  expressEngine/package.json
  expressEngine/route.js
  expressEngine/utils/login.js
Labels: feature

#88 feature/034
  README.md
Labels: doc

#128 feature/127
  expressEngine/.editorconfig
Labels: doc
